### ISSUE TITLE
ISO10642 & ISO14584 wrong direction socket pocket

### ISSUE THREAD

**Issue by Gesiima** [shaise/FreeCAD_FastenersWB#25] opened 2018-05-25 21:15 UTC
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.13780 (Git)
Build type: Release
Branch: master
Hash: 9fb122008b99ea2d30ed3e6f7cc93a3b7717cce5
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: German/Germany (de_DE)

![iso10642 iso14584](https://user-images.githubusercontent.com/23234214/40566505-4bec80b8-6071-11e8-9985-57f490401ac3.JPG)

**Comment by shaise** [comment] 2018-05-27 12:41
yes, problem verified. It happens freecad when moved from OCC v7.1 to OCC v7.2
Looking into it

**Comment by shaise** [comment] 2018-08-06 10:08
Sorry about that. I dug into the code, (its not mine) but could not find an easy fix. Do you know if ScrewMaker macro works for these types? If so, I will copy the solution from that. If not, I will try again as soon as I have time.

**Comment by Gesiima** [comment] 2018-09-02 12:02
Tested and works great! Thx für fix

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14495 (Git)
Build type: Release
Branch: master
Hash: c717d1121d888fe6cfbd8971b5f59311a34b37bc
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: German/Germany (de_DE)

**Comment by starcatter** [comment] 2022-10-08 20:16
Hi, is this issue back? I just installed what looks like the current version (last change in `readme.md` is `V0.4.15  04 Oct 2022`), and upon adding "hexagon socket countersunk head" screws got the following:

![image](https://user-images.githubusercontent.com/30572485/194726182-ed430c48-4238-461e-b3f2-6de6903516a0.png)

hexalobular screws on the left look ok, hex socket screws on the right are glitched again

**Comment by shaise** [comment] 2022-10-08 21:39
I will take a look at it, can you say what size and length are the hex screws?

**Comment by starcatter** [comment] 2022-10-09 00:03
![image](https://user-images.githubusercontent.com/30572485/194731678-11aea41a-d5e4-487c-9ee4-031e60b4107d.png)

**Comment by shaise** [comment] 2022-10-09 05:42
I can not reproduce this issue with the current freecad version:
![image](https://user-images.githubusercontent.com/5813568/194740013-efaa7e51-0206-451e-8afe-f3e9ab4f1cb6.png)
Perhaps you should update your freecad, version 18 is quite old.

**Comment by starcatter** [comment] 2022-10-09 11:40
You are right! It works fine in the current stable version:

![current](https://user-images.githubusercontent.com/30572485/194754160-7c9bbc19-cfb9-425a-90c8-58c428b3cc70.png)

Problem occurs in link branch, installed via snap:
![link](https://user-images.githubusercontent.com/30572485/194754162-70ac6aef-7b75-4985-84e8-b68a00a69be1.png)

As well as one built from arch package:
![link-aur](https://user-images.githubusercontent.com/30572485/194754797-2ce4d818-ce2a-430a-a455-e203a86a6fa2.png)


I also ensured all freecad installations share the same version of the fastener workbench. Looks like issue lies with the link branch.

**Comment by luzpaz** [comment] 2022-10-09 15:29
;Please let realthunder know. Closing ticket as this is related to Link branch

**Closed by luzpaz** 2022-10-09 15:29 UTC
Labels: waiting response

**Comment by shaise** [comment] 2022-10-13 07:00
I have merged @realthunder 's solution. However this fix is only for non flat countersunk screws so I wonder if it solves the issue. @starcatter , can you please check if it works now with the link branch?

**Comment by starcatter** [comment] 2022-10-15 12:53
Countersunk hex screw sockets are now modeled correctly: 
![image](https://user-images.githubusercontent.com/30572485/195987187-8b84decd-27b9-4572-96b4-15ea95b33cac.png)


However while playing around I noticed two things I think are new.

1 - set screws are sometimes modeled incorrectly, with the socket shape placed out of alignment:
![hex2](https://user-images.githubusercontent.com/30572485/195987214-641b9eb6-5a89-49e1-9e7f-d923692357f3.png)
Looks like it moved after generating the thread:
![hex3](https://user-images.githubusercontent.com/30572485/195987212-c47c652f-49c5-4551-ab06-92b4d90417d6.png)

2 - after some operations on fasteners (changing types eg. M8->M6, adding thread) an object named "Shape" appears. This happens randomly / isn't always reproducible, but consistently happens after a few operations.
![shapes](https://user-images.githubusercontent.com/30572485/195987252-53af1aaf-d304-4ec1-8fa8-d7b11f57adf1.png)
![shapes2](https://user-images.githubusercontent.com/30572485/195987251-c90ccb50-0771-41bb-bc4e-1bd95c19c35a.png)

Both might be separate issues, I'll test if either happens in the stable branch weekly build. Here's the model I'm testing on:
[5mm-plate.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/9792098/5mm-plate.zip)

**Comment by starcatter** [comment] 2022-10-15 13:06
The extra shape also appears in the weekly build:
![WEEKLY](https://user-images.githubusercontent.com/30572485/195987989-121ad6bc-b700-482f-9c3c-59d6fdfb1064.png)

[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30492 (Git) AppImage
Build type: Release
Branch: master
Hash: b4578fb3eae842eb510a1bc055d07d369a67ce94
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.15
  * Assembly3 0.11.3
[/code]

**Comment by shaise** [comment] 2022-10-16 10:41
Thanks for the report, working on it.
Can you save a file with a bad set screw and attach it?

**Comment by shaise** [comment] 2022-10-16 12:27
@starcatter 
I think I fixed both issues. (no need for example file) Can you please test?

shai

**Comment by starcatter** [comment] 2022-10-16 20:38
Looks fixed - I can't reproduce any of the issues after updating to the latest version. Thanks!
