### ISSUE TITLE
Insert fastener command doesn't work when diameter is changed #242

### ISSUE THREAD

**Issue by xoviat** [shaise/FreeCAD_FastenersWB#102] opened 2021-09-28 20:15 UTC
If both the 'fastener' type and 'diameter' is changed, then the insert fastener command fails.

```
09:29:15  At ~\AppData\Roaming\FreeCAD\Mod\fasteners\FSChangeParams.py Line 342
09:29:15  {'sclassname': 'class Base::ValueError', 'sErrMsg': "'#6' is not part of the enumeration", 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': "'#6' is not part of the enumeration", 'btranslatable': False, 'breported': True}: Inappropriate argument value (of correct type).
```

This may be a fasteners workbench issue? See Zolko-123/FreeCAD_Assembly4#242.

**Comment by luzpaz** [comment] 2022-03-23 11:43
@xoviat can you discuss this on the forum. It gets a lot more traffic/eyeballs than the Fastener issue queue. See https://forum.freecadweb.org/viewtopic.php?f=8&t=11429

**Comment by luzpaz** [comment] 2022-07-19 10:06
@xoviat ping

**Comment by luzpaz** [comment] 2022-08-22 13:47
@berberic2 do you mind weighing-in ?

**Comment by luzpaz** [comment] 2022-08-29 18:24
@shaise ping

**Comment by shaise** [comment] 2022-08-29 21:29
I can't reproduce this issue. Changing both fastener type and diameter seems to work even if I switch between Inch/Metric types. Need more info.

**Comment by berberic2** [comment] 2022-08-31 17:07
> @berberic2 do you mind weighing-in ?
Sorry, can not reproduce…

**Comment by luzpaz** [comment] 2022-08-31 17:56
@xoviat can you please add you full [about](https://wiki.freecad.org/About) info?

**Comment by alexneufeld** [comment] 2024-02-25 02:49
This should be closed, since no one has been able to reproduce the problem.

**Comment by shaise** [comment] 2024-02-25 07:49
closing

**Closed by shaise** 2024-02-25 07:49 UTC
Labels: waiting response
